### ISSUE TITLE
Will we add webcam to our situation?

### ISSUE THREAD

**Issue by zddhub** [hanystudy/coder-from-22nd-century#1]

**Comment by hanystudy** [comment]
It's very appreciate if you want a panoramic reality for C22. Actually that was indeed in our plan until lots of screen resolution & network limitation happened. 

Currently our focus is still on optimization, including resolution, network, and clean code. We will move on when we're satisfied, that will not be a long time.

**Comment by zddhub** [comment]
Cool ! 👍
